CREATE DATABASE scandiweb_test;

CREATE TABLE products (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(65, 2) UNSIGNED NOT NULL,
    productType VARCHAR(255) NOT NULL,
    size INT(255) UNSIGNED,
    weight INT(255) UNSIGNED,
    height INT(255) UNSIGNED,
    width INT(255) UNSIGNED,
    length INT(255) UNSIGNED,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
